- hosts: kuber
  become_user: ubuntu
  vars:
  - ansible_become_pass: {{pass}}
  tasks:
  - name: coping the files 
    copy: 
      src: jsapp.yaml
      dest: /home/ubuntu
  - name: restart docker
    service:
      name: docker
      state: restarted
    become: true
    ignore_errors: yes
  - name: running the deployment
    command: kubectl apply -f jsapp.yaml
  
