- hosts: kuber
  become_user: ubuntu
  tasks:
  - name: coping the files 
    copy: 
     src: jsapp.yaml
     dest: /home/ubuntu
  - name: restart docker
    service: docker
    state: restarted
    become: true
  - name: running the deployment
    command: kubectl apply -f jsapp.yaml
  
