apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dep
  name: dep
spec:
  replicas: 3
  selector:
    matchLabels:
      run: pod
  template:
    metadata:
      labels:
       run: pod
    spec:
      containers:
      - image: rithvikyadavdocker/jsapp:latest
        name: jsapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: pod
  name: serv
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    run: pod
  type: NodePort
